// GENERATED BY HAND FOR OFFLINE USE.
// ignore_for_file: type=lint

part of 'sale.dart';

class SaleAdapter extends TypeAdapter<Sale> {
  @override
  final int typeId = 3;

  @override
  Sale read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (int i = 0; i < numOfFields; i++) {
      fields[reader.readByte()] = reader.read();
    }
    return Sale(
      id: fields[0] as int,
      date: fields[1] as DateTime,
      totalItems: fields[2] as int,
      totalValue: fields[3] as double,
      items: (fields[4] as List).cast<SaleItem>(),
      customerName: fields[5] as String?,
      note: fields[6] as String?,
    );
  }

  @override
  void write(BinaryWriter writer, Sale obj) {
    writer
      ..writeByte(7)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.date)
      ..writeByte(2)
      ..write(obj.totalItems)
      ..writeByte(3)
      ..write(obj.totalValue)
      ..writeByte(4)
      ..write(obj.items)
      ..writeByte(5)
      ..write(obj.customerName)
      ..writeByte(6)
      ..write(obj.note);
  }
}
